FROM mcr.microsoft.com/windows/servercore/iis
SHELL ["powershell", "-command"]

RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*


RUN Install-WindowsFeature Web-ASP;
RUN Install-WindowsFeature Web-ISAPI-Filter;

RUN Remove-Website -Name 'Default Web Site';

WORKDIR /inetpub/wwwroot