name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: docker-classic-asp
  REPO_OWNER: ${{ github.repository_owner }}
  CR_HOST: ""
  CR_PAT: ${{ secrets.CR_PAT }}
  CR_USER: ${{ secrets.CR_USER }}

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: windows-2019
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Log into Dockerhub
        run: docker login -u ${{ secrets.CR_USER }} -p ${{ secrets.CR_PAT }}
      
      - name: Run tests on main
        run: |
          docker build . --file Dockerfile --tag $Env:IMAGE_NAME --build-arg SVCUSER="testuser" --build-arg SVCPASS="TeStP@ssW0rd" --build-arg SITENAME="test.com"

      - name: Push main
        run: |
          $IMAGE_ID="${Env:CR_USER}/${Env:IMAGE_NAME}"
          $VERSION=(($Env:GITHUB_REF) -replace "master","latest") -replace "refs/heads/",""

          docker tag "${Env:IMAGE_NAME}" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"

      - name: Run tests on minimal
        run: |
          docker build . --file Dockerfile-minimal --tag ${Env:IMAGE_NAME}-minimal

      - name: Push minimal
        run: |
          $IMAGE_ID="${Env:CR_USER}/${Env:IMAGE_NAME}-minimal"
          $VERSION=(($Env:GITHUB_REF-minimal) -replace "master","latest") -replace "refs/heads/",""

          docker tag "${Env:IMAGE_NAME}-minimal" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"
